In [13]:
import tushare as ts
import sys
import pandas as pd
import numpy as np

sys.path.append('C:\\Users\\longf.DESKTOP-7QSFE46\\GitHub\\A-Stock-Prediction-System-with-GAN-and-DRL')

with open('C:\\Users\\longf.DESKTOP-7QSFE46\\GitHub\\A-Stock-Prediction-System-with-GAN-and-DRL\\bin\\base\\token.tkn','r') as token:
    mytoken = token.readline().rstrip('\n')
    print('Your token is ' + mytoken)
    
ts.set_token(mytoken)
data = ts.pro_bar(ts_code='600690.SH', start_date='20190201', end_date='20190301', asset='E', freq='1min', ma=[7, 21])

data

Your token is 52d1d7b3ade4d917050699b12c7f2327fd9c2afa2e21e66f2633a88b

,ts_code,trade_time,open,high,low,close,vol,amount,trade_date,pre_close,ma7,ma_v_7,ma21,ma_v_21
0,600690.SH,2019-02-28 15:00:00,16.48,16.48,16.48,16.48,598800.0,9868224.0,20190228,16.54,16.52,342124.29,16.55,267489.10
1,600690.SH,2019-02-28 14:59:00,16.54,16.54,16.54,16.54,0.0,0.0,20190228,16.54,16.53,371329.29,16.56,242346.33
2,600690.SH,2019-02-28 14:58:00,16.54,16.54,16.54,16.54,5700.0,94263.0,20190228,16.53,16.53,423352.86,16.56,249009.10
3,600690.SH,2019-02-28 14:57:00,16.50,16.54,16.48,16.53,398505.0,6573078.0,20190228,16.50,16.53,472403.57,16.56,253264.67
4,600690.SH,2019-02-28 14:56:00,16.55,16.56,16.50,16.50,777598.0,12843899.0,20190228,16.54,16.54,441165.71,16.57,241061.57
5,600690.SH,2019-02-28 14:55:00,16.53,16.55,16.53,16.54,142018.0,2348061.0,20190228,16.53,16.54,339697.43,16.57,208752.14
6,600690.SH,2019-02-28 14:54:00,16.51,16.55,16.51,16.53,472249.0,7798300.0,20190228,16.56,16.55,359537.71,16.57,215360.81
7,600690.SH,2019-02-28 14:53:00,16.51,16.56,16.51,16.56,803235.0,13259835.0,20190228,16.51,16.55,328046.29,16.58,199209.90
8,600690.SH,2019-02-28 14:52:00,16.55,16.55,16.50,16.51,364165.0,6016788.0,20190228,16.55,16.55,246795.57,16.58,170905.38
9,600690.SH,2019-02-28 14:51:00,16.55,16.55,16.51,16.55,349055.0,5768597.0,20190228,16.56,16.56,207243.43,16.58,167164.19
10,600690.SH,2019-02-28 14:50:00,16.56,16.57,16.52,16.56,179840.0,2974495.0,20190228,16.56,16.57,168078.43,16.58,170180.62
11,600690.SH,2019-02-28 14:49:00,16.53,16.57,16.53,16.56,67320.0,1113547.0,20190228,16.57,16.58,159841.14,16.58,169754.90
12,600690.SH,2019-02-28 14:48:00,16.54,16.57,16.52,16.57,280900.0,4642041.0,20190228,16.56,16.58,171116.14,16.58,170244.19
13,600690.SH,2019-02-28 14:47:00,16.56,16.56,16.53,16.56,251809.0,4166903.0,20190228,16.55,16.58,146959.00,16.58,168912.57
14,600690.SH,2019-02-28 14:46:00,16.61,16.61,16.55,16.55,234480.0,3886024.0,20190228,16.60,16.58,132296.71,16.58,160769.29
15,600690.SH,2019-02-28 14:45:00,16.61,16.61,16.59,16.60,87300.0,1448792.0,20190228,16.61,16.59,108914.14,16.58,151994.05
16,600690.SH,2019-02-28 14:44:00,16.60,16.61,16.60,16.61,74900.0,1243329.0,20190228,16.58,16.59,116431.00,16.58,151436.90
17,600690.SH,2019-02-28 14:43:00,16.61,16.61,16.58,16.58,122179.0,2027672.0,20190228,16.60,16.59,119312.00,16.58,155790.29
18,600690.SH,2019-02-28 14:42:00,16.58,16.60,16.57,16.60,146245.0,2426158.0,20190228,16.58,16.59,122177.86,16.58,155281.76
19,600690.SH,2019-02-28 14:41:00,16.58,16.60,16.57,16.58,111800.0,1854016.0,20190228,16.57,16.59,115442.86,16.57,153936.76
20,600690.SH,2019-02-28 14:40:00,16.59,16.60,16.57,16.57,149173.0,2473445.0,20190228,16.59,16.59,139585.71,16.57,151719.95
21,600690.SH,2019-02-28 14:39:00,16.59,16.60,16.58,16.59,70802.0,1174746.0,20190228,16.58,16.59,137286.71,16.57,147390.19
22,600690.SH,2019-02-28 14:38:00,16.60,16.60,16.58,16.58,139918.0,2322150.0,20190228,16.60,16.59,157006.43,16.57,150802.14
23,600690.SH,2019-02-28 14:37:00,16.60,16.60,16.59,16.60,95067.0,1577405.0,20190228,16.59,16.58,177818.14,16.57,149686.00
24,600690.SH,2019-02-28 14:36:00,16.60,16.60,16.59,16.59,142240.0,2360390.0,20190228,16.60,16.58,223151.43,16.57,162774.62
25,600690.SH,2019-02-28 14:35:00,16.60,16.61,16.59,16.60,99100.0,1645149.0,20190228,16.60,16.57,227245.71,16.57,158463.19
26,600690.SH,2019-02-28 14:34:00,16.58,16.60,16.57,16.60,280800.0,4657205.0,20190228,16.58,16.56,224173.57,16.57,158539.38
27,600690.SH,2019-02-28 14:33:00,16.58,16.58,16.57,16.58,133080.0,2205808.0,20190228,16.57,16.56,220193.00,16.57,148644.14
28,600690.SH,2019-02-28 14:32:00,16.58,16.58,16.55,16.57,208840.0,3458326.0,20190228,16.55,16.56,212724.43,16.57,146812.38
29,600690.SH,2019-02-28 14:31:00,16.54,16.55,16.53,16.55,285600.0,4724869.0,20190228,16.54,16.56,190061.57,16.57,141515.95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3585,600690.SH,2019-02-01 09:59:00,16.00,16.02,16.00,16.02,63800.0,1021437.0,20190201,16.00,16.02,117385.71,16.03,170919.05
3586,600690.SH,2019-02-01 09:58:00,16.00,16.01,15.98,16.00,100200.0,1602700.0,20190201,16.00,16.02,133500.00,16.03,182638.10
3587,600690.SH,2019-02-01 09:57:00,16.03,16.03,15.99,16.00,234700.0,3757919.0,20190201,16.04,16.03,151714.29,16.04,196880.95
3588,600690.SH,2019-02-01 09:56:00,16.03,16.04,16.03,16.04,61600.0,987685.0,20190201,16.04,16.03,154757.14,16.05,198185.71
3589,600690.SH,2019-02-01 09:55:00,16.04,16.05,16.02,16.04,97300.0,1559947.0,20190201,16.04,16.02,164500.00,16.05,209010.86
3590,600690.SH,2019-02-01 09:54:00,16.04,16.05,16.02,16.04,140900.0,2260479.0,20190201,16.02,16.01,169057.14,16.06,212382.29
3591,600690.SH,2019-02-01 09:53:00,16.02,16.04,16.02,16.02,123200.0,1975068.0,20190201,16.01,16.00,192528.57,16.07,217410.86
3592,600690.SH,2019-02-01 09:52:00,16.02,16.06,16.01,16.01,176600.0,2831739.0,20190201,16.03,16.00,215500.00,16.08,227129.90
3593,600690.SH,2019-02-01 09:51:00,16.05,16.09,16.00,16.03,227700.0,3652556.0,20190201,16.05,16.00,218757.14,16.09,249415.62
3594,600690.SH,2019-02-01 09:50:00,15.99,16.08,15.98,16.05,256000.0,4101649.0,20190201,15.98,16.00,204814.29,16.10,251696.57
3595,600690.SH,2019-02-01 09:49:00,15.97,15.99,15.96,15.98,129800.0,2073360.0,20190201,15.96,16.00,190471.43,NaN,NaN
3596,600690.SH,2019-02-01 09:48:00,15.98,15.98,15.96,15.96,129200.0,2063606.0,20190201,15.98,16.02,197157.14,NaN,NaN
3597,600690.SH,2019-02-01 09:47:00,16.01,16.02,15.98,15.98,305200.0,4884191.0,20190201,16.00,16.04,199514.29,NaN,NaN
3598,600690.SH,2019-02-01 09:46:00,16.04,16.05,16.00,16.00,284000.0,4551064.0,20190201,16.03,16.06,171200.00,NaN,NaN
3599,600690.SH,2019-02-01 09:45:00,16.03,16.05,16.02,16.03,199400.0,3197110.0,20190201,16.03,16.07,179871.43,NaN,NaN
3600,600690.SH,2019-02-01 09:44:00,16.05,16.05,16.03,16.03,130100.0,2085766.0,20190201,16.05,16.08,195657.14,NaN,NaN
3601,600690.SH,2019-02-01 09:43:00,16.08,16.09,16.05,16.05,155600.0,2499956.0,20190201,16.08,16.09,234114.29,NaN,NaN
3602,600690.SH,2019-02-01 09:42:00,16.09,16.09,16.06,16.08,176600.0,2839563.0,20190201,16.09,16.11,249328.57,NaN,NaN
3603,600690.SH,2019-02-01 09:41:00,16.13,16.14,16.08,16.09,145700.0,2347129.0,20190201,16.14,16.12,265375.43,NaN,NaN
3604,600690.SH,2019-02-01 09:40:00,16.05,16.14,16.05,16.14,107000.0,1725404.0,20190201,16.05,16.13,268575.43,NaN,NaN
3605,600690.SH,2019-02-01 09:39:00,16.14,16.15,16.05,16.05,344700.0,5541067.0,20190201,16.09,16.14,288504.00,NaN,NaN
3606,600690.SH,2019-02-01 09:38:00,16.12,16.17,16.09,16.09,309900.0,4996018.0,20190201,16.13,16.16,286018.29,NaN,NaN
3607,600690.SH,2019-02-01 09:37:00,16.16,16.20,16.13,16.13,399300.0,6457961.0,20190201,16.16,16.18,333832.57,NaN,NaN
3608,600690.SH,2019-02-01 09:36:00,16.19,16.20,16.15,16.16,262100.0,4241321.0,20190201,16.16,16.20,316161.14,NaN,NaN
3609,600690.SH,2019-02-01 09:35:00,16.19,16.21,16.15,16.16,288928.0,4677928.0,20190201,16.21,NaN,NaN,NaN,NaN
3610,600690.SH,2019-02-01 09:34:00,16.22,16.22,16.20,16.21,168100.0,2724527.0,20190201,16.19,NaN,NaN,NaN,NaN
3611,600690.SH,2019-02-01 09:33:00,16.18,16.21,16.15,16.19,246500.0,3993148.0,20190201,16.21,NaN,NaN,NaN,NaN
3612,600690.SH,2019-02-01 09:32:00,16.24,16.24,16.13,16.21,327300.0,5302835.0,20190201,16.19,NaN,NaN,NaN,NaN
3613,600690.SH,2019-02-01 09:31:00,16.28,16.28,16.19,16.19,644600.0,10467383.0,20190201,16.25,NaN,NaN,NaN,NaN
3614,600690.SH,2019-02-01 09:30:00,16.25,16.25,16.25,16.25,275600.0,4478500.0,20190201,NaN,NaN,NaN,NaN,NaN

In [14]:
from matplotlib import pyplot as plt


plt.figure()
time = pd.to_datetime(data['trade_time'], format='%Y-%m-%d %H:%M:%S')

plt.plot(time, data['close'])
plt.show()

plt.plot(time, data['ma7'])
plt.show()

C:\Users\longf.DESKTOP-7QSFE46\Anaconda3\envs\keras\lib\site-packages\pandas\plotting\_converter.py:129: FutureWarning: Using an implicitly registered datetime converter for a matplotlib plotting method. The converter was registered by pandas on import. Future versions of pandas will require you to explicitly register matplotlib converters.

To register the converters:
	>>> from pandas.plotting import register_matplotlib_converters
	>>> register_matplotlib_converters()
  warnings.warn(msg, FutureWarning)

In [15]:
import arrow

now = arrow.now()
print(now.date())
print(now.time())

2019-07-18
09:35:16.826377

In [18]:
print(now.shift(months=-5).date())

2019-02-18